"""Initial migration

Revision ID: 23aaeb6b2508
Revises: 
Create Date: 2025-11-04 21:42:12.355893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '23aaeb6b2508'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('brand_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_name'), 'brand', ['name'], unique=True)
    op.create_table('mount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('flange_distance', sa.Float(), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mount_name'), 'mount', ['name'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hash_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', 'EDITOR', 'VIEWER', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('brandmount',
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('mount_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('compatibility_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['mount_id'], ['mount.id'], ),
    sa.PrimaryKeyConstraint('brand_id', 'mount_id')
    )
    op.create_table('camera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('mount_id', sa.Integer(), nullable=False),
    sa.Column('sensor_size', sa.Enum('MEDIUM_FORMAT', 'FULL_FRAME', 'APS_C', 'M43', 'ONE_INCH', 'OTHER', name='sensorsize'), nullable=True),
    sa.Column('series', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('megapixels', sa.Float(), nullable=True),
    sa.Column('ibis_level', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('has_hot_shoe', sa.Boolean(), nullable=False),
    sa.Column('has_built_in_flash', sa.Boolean(), nullable=False),
    sa.Column('has_wifi', sa.Boolean(), nullable=False),
    sa.Column('has_bluetooth', sa.Boolean(), nullable=False),
    sa.Column('release_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('release_price', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['mount_id'], ['mount.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camera_model'), 'camera', ['model'], unique=False)
    op.create_table('lens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('mount_id', sa.Integer(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('series', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('min_focal_length', sa.Float(), nullable=False),
    sa.Column('max_focal_length', sa.Float(), nullable=False),
    sa.Column('lens_type', sa.Enum('ZOOM', 'PRIME', name='lenstype'), nullable=False),
    sa.Column('max_aperture_min', sa.Float(), nullable=False),
    sa.Column('max_aperture_max', sa.Float(), nullable=True),
    sa.Column('is_constant_aperture', sa.Boolean(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('diameter', sa.Float(), nullable=True),
    sa.Column('filter_size', sa.Float(), nullable=True),
    sa.Column('focus_type', sa.Enum('AUTO', 'MANUAL', name='focustype'), nullable=False),
    sa.Column('has_stabilization', sa.Boolean(), nullable=False),
    sa.Column('min_focus_distance', sa.Float(), nullable=True),
    sa.Column('magnification', sa.Float(), nullable=True),
    sa.Column('release_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('release_price', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['mount_id'], ['mount.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lens_model'), 'lens', ['model'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lens_model'), table_name='lens')
    op.drop_table('lens')
    op.drop_index(op.f('ix_camera_model'), table_name='camera')
    op.drop_table('camera')
    op.drop_table('brandmount')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_mount_name'), table_name='mount')
    op.drop_table('mount')
    op.drop_index(op.f('ix_brand_name'), table_name='brand')
    op.drop_table('brand')
    # ### end Alembic commands ###
